/// Pays du monde : nom, drapeau et indicatif téléphonique, plus les
/// opérateurs de porte-monnaie électronique (Mobile Money) connus par pays.
library;

class Country {
  const Country(this.code, this.name, this.dialCode);

  /// Code ISO 3166-1 alpha-2 (ex. `BF`).
  final String code;
  final String name;

  /// Indicatif sans le `+` (ex. `226`).
  final String dialCode;

  /// Drapeau en emoji, construit à partir du code ISO.
  String get flag => String.fromCharCodes(
    code.toUpperCase().codeUnits.map((unit) => 0x1F1E6 + unit - 0x41),
  );

  /// Opérateurs de porte-monnaie électronique de ce pays (peut être vide).
  List<String> get mobileMoneyOperators =>
      mobileMoneyByCountry[code] ?? const [];

  @override
  bool operator ==(Object other) => other is Country && other.code == code;

  @override
  int get hashCode => code.hashCode;
}

/// Pays utilisé quand la position est inconnue.
const defaultCountryCode = 'BF';

Country get defaultCountry => countryByCode(defaultCountryCode)!;

Country? countryByCode(String? code) {
  if (code == null) return null;
  final upper = code.toUpperCase();
  for (final country in countries) {
    if (country.code == upper) return country;
  }
  return null;
}

/// Pays dont l'indicatif commence [number] (`+226 70…`), le plus long d'abord.
/// [preferred] départage les indicatifs partagés (ex. +1 : États-Unis, Canada…).
Country? countryOfNumber(String number, {Country? preferred}) {
  final digits = number.replaceAll(RegExp(r'[^0-9]'), '');
  if (!number.trim().startsWith('+') || digits.isEmpty) return null;
  if (preferred != null && digits.startsWith(preferred.dialCode)) {
    return preferred;
  }
  Country? best;
  for (final country in countries) {
    if (digits.startsWith(country.dialCode) &&
        (best == null || country.dialCode.length > best.dialCode.length)) {
      best = country;
    }
  }
  if (best == null) return null;
  return countryByCode(_mainCountryOfDialCode[best.dialCode]) ?? best;
}

/// Pays retenu quand plusieurs partagent un indicatif.
const _mainCountryOfDialCode = {
  '1': 'US',
  '7': 'RU',
  '39': 'IT',
  '44': 'GB',
  '61': 'AU',
  '212': 'MA',
  '262': 'RE',
  '358': 'FI',
  '590': 'GP',
};

/// Opérateurs de Mobile Money par pays (code ISO). Ailleurs : « Autre ».
const mobileMoneyByCountry = <String, List<String>>{
  'BF': [
    'ORANGE MONEY',
    'MOOV MONEY',
    'WAVE',
    'LIGDICASH',
    'SANK MONEY',
    'TELECEL MONEY',
    'WIZALL MONEY',
  ],
  'CI': ['ORANGE MONEY', 'MTN MOBILE MONEY', 'MOOV MONEY', 'WAVE', 'DJAMO'],
  'SN': ['ORANGE MONEY', 'WAVE', 'FREE MONEY', 'WIZALL MONEY', 'E-MONEY'],
  'ML': ['ORANGE MONEY', 'MOOV MONEY', 'WAVE', 'SAMA MONEY'],
  'NE': ['AIRTEL MONEY', 'MOOV MONEY', 'ZAMANI CASH', 'NITA'],
  'TG': ['FLOOZ (MOOV)', 'MIXX BY YAS (T-MONEY)'],
  'BJ': ['MTN MOBILE MONEY', 'MOOV MONEY', 'CELTIIS CASH'],
  'GN': ['ORANGE MONEY', 'MTN MOBILE MONEY'],
  'GW': ['ORANGE MONEY', 'MTN MOBILE MONEY'],
  'MR': ['BANKILY', 'MASRVI', 'SEDAD'],
  'GM': ['WAVE', 'AFRICELL MONEY', 'QMONEY'],
  'SL': ['ORANGE MONEY', 'AFRICELL MONEY'],
  'LR': ['MTN MOBILE MONEY', 'ORANGE MONEY'],
  'GH': ['MTN MOBILE MONEY', 'TELECEL CASH', 'AT MONEY'],
  'NG': ['OPAY', 'PALMPAY', 'MOMO PSB', 'PAGA'],
  'CM': ['ORANGE MONEY', 'MTN MOBILE MONEY'],
  'TD': ['AIRTEL MONEY', 'MOOV MONEY'],
  'CF': ['ORANGE MONEY', 'MOOV MONEY'],
  'GA': ['AIRTEL MONEY', 'MOOV MONEY'],
  'CG': ['MTN MOBILE MONEY', 'AIRTEL MONEY'],
  'CD': ['M-PESA', 'AIRTEL MONEY', 'ORANGE MONEY', 'AFRICELL MONEY'],
  'GQ': ['MUNI DINERO'],
  'BI': ['LUMICASH', 'ECOCASH'],
  'RW': ['MTN MOBILE MONEY', 'AIRTEL MONEY'],
  'UG': ['MTN MOBILE MONEY', 'AIRTEL MONEY'],
  'KE': ['M-PESA', 'AIRTEL MONEY', 'T-KASH'],
  'TZ': ['M-PESA', 'MIXX BY YAS', 'AIRTEL MONEY', 'HALOPESA'],
  'ET': ['TELEBIRR', 'M-PESA'],
  'SO': ['EVC PLUS', 'ZAAD', 'SAHAL'],
  'DJ': ['D-MONEY', 'WAAFI'],
  'MG': ['MVOLA', 'ORANGE MONEY', 'AIRTEL MONEY'],
  'KM': ['HURI MONEY', 'MVOLA'],
  'MZ': ['M-PESA', 'E-MOLA', 'MKESH'],
  'MW': ['AIRTEL MONEY', 'TNM MPAMBA'],
  'ZM': ['MTN MOBILE MONEY', 'AIRTEL MONEY', 'ZAMTEL KWACHA'],
  'ZW': ['ECOCASH', 'ONEMONEY'],
  'NA': ['MTC MAERI', 'BLUE WALLET'],
  'BW': ['ORANGE MONEY', 'MYZAKA', 'SMEGA'],
  'LS': ['M-PESA', 'ECOCASH'],
  'SZ': ['MTN MOMO', 'E-MALI'],
  'ZA': ['MTN MOMO', 'VODAPAY'],
  'AO': ['UNITEL MONEY', 'MULTICAIXA EXPRESS'],
  'ST': ['DIMIX'],
  'CV': ['VINTI4'],
  'SS': ['MGURUSH', 'MTN MOMO'],
  'SD': ['BANKAK', 'MYCASHI'],
  'MA': ['CASH PLUS', 'ORANGE MONEY', 'INWI MONEY'],
  'DZ': ['BARIDIMOB'],
  'TN': ['D17', 'MOBIFLOUS'],
  'EG': ['VODAFONE CASH', 'ORANGE CASH', 'ETISALAT CASH', 'INSTAPAY'],
  'IN': ['PAYTM', 'PHONEPE', 'GOOGLE PAY', 'BHIM UPI'],
  'PK': ['JAZZCASH', 'EASYPAISA'],
  'BD': ['BKASH', 'NAGAD', 'ROCKET'],
  'PH': ['GCASH', 'MAYA'],
  'ID': ['GOPAY', 'OVO', 'DANA'],
  'KH': ['WING', 'ABA PAY'],
  'NP': ['ESEWA', 'KHALTI'],
  'HT': ['MONCASH', 'NATCASH'],
  'FR': ['LYDIA', 'PAYPAL', 'WERO'],
  'BE': ['PAYCONIQ', 'PAYPAL', 'WERO'],
  'CH': ['TWINT', 'PAYPAL'],
  'CA': ['INTERAC', 'PAYPAL'],
  'US': ['ZELLE', 'CASH APP', 'VENMO', 'PAYPAL'],
  'GB': ['PAYPAL', 'REVOLUT'],
  'BR': ['PIX', 'MERCADO PAGO', 'PICPAY'],
  'MX': ['MERCADO PAGO', 'CODI'],
  'CN': ['ALIPAY', 'WECHAT PAY'],
};

/// Tous les pays et territoires, triés par nom.
const countries = <Country>[
  Country('AF', 'Afghanistan', '93'),
  Country('ZA', 'Afrique du Sud', '27'),
  Country('AL', 'Albanie', '355'),
  Country('DZ', 'Algérie', '213'),
  Country('DE', 'Allemagne', '49'),
  Country('AD', 'Andorre', '376'),
  Country('AO', 'Angola', '244'),
  Country('AI', 'Anguilla', '1264'),
  Country('AG', 'Antigua-et-Barbuda', '1268'),
  Country('SA', 'Arabie saoudite', '966'),
  Country('AR', 'Argentine', '54'),
  Country('AM', 'Arménie', '374'),
  Country('AW', 'Aruba', '297'),
  Country('AU', 'Australie', '61'),
  Country('AT', 'Autriche', '43'),
  Country('AZ', 'Azerbaïdjan', '994'),
  Country('BS', 'Bahamas', '1242'),
  Country('BH', 'Bahreïn', '973'),
  Country('BD', 'Bangladesh', '880'),
  Country('BB', 'Barbade', '1246'),
  Country('BE', 'Belgique', '32'),
  Country('BZ', 'Belize', '501'),
  Country('BJ', 'Bénin', '229'),
  Country('BM', 'Bermudes', '1441'),
  Country('BT', 'Bhoutan', '975'),
  Country('BY', 'Biélorussie', '375'),
  Country('MM', 'Birmanie (Myanmar)', '95'),
  Country('BO', 'Bolivie', '591'),
  Country('BA', 'Bosnie-Herzégovine', '387'),
  Country('BW', 'Botswana', '267'),
  Country('BR', 'Brésil', '55'),
  Country('BN', 'Brunei', '673'),
  Country('BG', 'Bulgarie', '359'),
  Country('BF', 'Burkina Faso', '226'),
  Country('BI', 'Burundi', '257'),
  Country('KH', 'Cambodge', '855'),
  Country('CM', 'Cameroun', '237'),
  Country('CA', 'Canada', '1'),
  Country('CV', 'Cap-Vert', '238'),
  Country('CL', 'Chili', '56'),
  Country('CN', 'Chine', '86'),
  Country('CY', 'Chypre', '357'),
  Country('CO', 'Colombie', '57'),
  Country('KM', 'Comores', '269'),
  Country('CG', 'Congo', '242'),
  Country('CD', 'Congo (RDC)', '243'),
  Country('KP', 'Corée du Nord', '850'),
  Country('KR', 'Corée du Sud', '82'),
  Country('CR', 'Costa Rica', '506'),
  Country('CI', 'Côte d’Ivoire', '225'),
  Country('HR', 'Croatie', '385'),
  Country('CU', 'Cuba', '53'),
  Country('CW', 'Curaçao', '599'),
  Country('DK', 'Danemark', '45'),
  Country('DJ', 'Djibouti', '253'),
  Country('DM', 'Dominique', '1767'),
  Country('EG', 'Égypte', '20'),
  Country('AE', 'Émirats arabes unis', '971'),
  Country('EC', 'Équateur', '593'),
  Country('ER', 'Érythrée', '291'),
  Country('ES', 'Espagne', '34'),
  Country('EE', 'Estonie', '372'),
  Country('SZ', 'Eswatini', '268'),
  Country('US', 'États-Unis', '1'),
  Country('ET', 'Éthiopie', '251'),
  Country('FJ', 'Fidji', '679'),
  Country('FI', 'Finlande', '358'),
  Country('FR', 'France', '33'),
  Country('GA', 'Gabon', '241'),
  Country('GM', 'Gambie', '220'),
  Country('GE', 'Géorgie', '995'),
  Country('GH', 'Ghana', '233'),
  Country('GI', 'Gibraltar', '350'),
  Country('GR', 'Grèce', '30'),
  Country('GD', 'Grenade', '1473'),
  Country('GL', 'Groenland', '299'),
  Country('GP', 'Guadeloupe', '590'),
  Country('GU', 'Guam', '1671'),
  Country('GT', 'Guatemala', '502'),
  Country('GG', 'Guernesey', '44'),
  Country('GN', 'Guinée', '224'),
  Country('GQ', 'Guinée équatoriale', '240'),
  Country('GW', 'Guinée-Bissau', '245'),
  Country('GY', 'Guyana', '592'),
  Country('GF', 'Guyane française', '594'),
  Country('HT', 'Haïti', '509'),
  Country('HN', 'Honduras', '504'),
  Country('HK', 'Hong Kong', '852'),
  Country('HU', 'Hongrie', '36'),
  Country('IM', 'Île de Man', '44'),
  Country('CX', 'Île Christmas', '61'),
  Country('NF', 'Île Norfolk', '672'),
  Country('AX', 'Îles Åland', '358'),
  Country('KY', 'Îles Caïmans', '1345'),
  Country('CC', 'Îles Cocos', '61'),
  Country('CK', 'Îles Cook', '682'),
  Country('FO', 'Îles Féroé', '298'),
  Country('FK', 'Îles Malouines', '500'),
  Country('MP', 'Îles Mariannes du Nord', '1670'),
  Country('MH', 'Îles Marshall', '692'),
  Country('SB', 'Îles Salomon', '677'),
  Country('TC', 'Îles Turques-et-Caïques', '1649'),
  Country('VG', 'Îles Vierges britanniques', '1284'),
  Country('VI', 'Îles Vierges des États-Unis', '1340'),
  Country('IN', 'Inde', '91'),
  Country('ID', 'Indonésie', '62'),
  Country('IQ', 'Irak', '964'),
  Country('IR', 'Iran', '98'),
  Country('IE', 'Irlande', '353'),
  Country('IS', 'Islande', '354'),
  Country('IL', 'Israël', '972'),
  Country('IT', 'Italie', '39'),
  Country('JM', 'Jamaïque', '1876'),
  Country('JP', 'Japon', '81'),
  Country('JE', 'Jersey', '44'),
  Country('JO', 'Jordanie', '962'),
  Country('KZ', 'Kazakhstan', '7'),
  Country('KE', 'Kenya', '254'),
  Country('KG', 'Kirghizistan', '996'),
  Country('KI', 'Kiribati', '686'),
  Country('XK', 'Kosovo', '383'),
  Country('KW', 'Koweït', '965'),
  Country('LA', 'Laos', '856'),
  Country('LS', 'Lesotho', '266'),
  Country('LV', 'Lettonie', '371'),
  Country('LB', 'Liban', '961'),
  Country('LR', 'Liberia', '231'),
  Country('LY', 'Libye', '218'),
  Country('LI', 'Liechtenstein', '423'),
  Country('LT', 'Lituanie', '370'),
  Country('LU', 'Luxembourg', '352'),
  Country('MO', 'Macao', '853'),
  Country('MK', 'Macédoine du Nord', '389'),
  Country('MG', 'Madagascar', '261'),
  Country('MY', 'Malaisie', '60'),
  Country('MW', 'Malawi', '265'),
  Country('MV', 'Maldives', '960'),
  Country('ML', 'Mali', '223'),
  Country('MT', 'Malte', '356'),
  Country('MA', 'Maroc', '212'),
  Country('MQ', 'Martinique', '596'),
  Country('MU', 'Maurice', '230'),
  Country('MR', 'Mauritanie', '222'),
  Country('YT', 'Mayotte', '262'),
  Country('MX', 'Mexique', '52'),
  Country('FM', 'Micronésie', '691'),
  Country('MD', 'Moldavie', '373'),
  Country('MC', 'Monaco', '377'),
  Country('MN', 'Mongolie', '976'),
  Country('ME', 'Monténégro', '382'),
  Country('MS', 'Montserrat', '1664'),
  Country('MZ', 'Mozambique', '258'),
  Country('NA', 'Namibie', '264'),
  Country('NR', 'Nauru', '674'),
  Country('NP', 'Népal', '977'),
  Country('NI', 'Nicaragua', '505'),
  Country('NE', 'Niger', '227'),
  Country('NG', 'Nigeria', '234'),
  Country('NU', 'Niue', '683'),
  Country('NO', 'Norvège', '47'),
  Country('NC', 'Nouvelle-Calédonie', '687'),
  Country('NZ', 'Nouvelle-Zélande', '64'),
  Country('OM', 'Oman', '968'),
  Country('UG', 'Ouganda', '256'),
  Country('UZ', 'Ouzbékistan', '998'),
  Country('PK', 'Pakistan', '92'),
  Country('PW', 'Palaos', '680'),
  Country('PS', 'Palestine', '970'),
  Country('PA', 'Panama', '507'),
  Country('PG', 'Papouasie-Nouvelle-Guinée', '675'),
  Country('PY', 'Paraguay', '595'),
  Country('NL', 'Pays-Bas', '31'),
  Country('PE', 'Pérou', '51'),
  Country('PH', 'Philippines', '63'),
  Country('PL', 'Pologne', '48'),
  Country('PF', 'Polynésie française', '689'),
  Country('PR', 'Porto Rico', '1787'),
  Country('PT', 'Portugal', '351'),
  Country('QA', 'Qatar', '974'),
  Country('CF', 'République centrafricaine', '236'),
  Country('DO', 'République dominicaine', '1809'),
  Country('CZ', 'République tchèque', '420'),
  Country('RE', 'La Réunion', '262'),
  Country('RO', 'Roumanie', '40'),
  Country('GB', 'Royaume-Uni', '44'),
  Country('RU', 'Russie', '7'),
  Country('RW', 'Rwanda', '250'),
  Country('EH', 'Sahara occidental', '212'),
  Country('BL', 'Saint-Barthélemy', '590'),
  Country('KN', 'Saint-Christophe-et-Niévès', '1869'),
  Country('SM', 'Saint-Marin', '378'),
  Country('MF', 'Saint-Martin', '590'),
  Country('PM', 'Saint-Pierre-et-Miquelon', '508'),
  Country('VC', 'Saint-Vincent-et-les-Grenadines', '1784'),
  Country('SH', 'Sainte-Hélène', '290'),
  Country('LC', 'Sainte-Lucie', '1758'),
  Country('SV', 'Salvador', '503'),
  Country('WS', 'Samoa', '685'),
  Country('AS', 'Samoa américaines', '1684'),
  Country('ST', 'Sao Tomé-et-Principe', '239'),
  Country('SN', 'Sénégal', '221'),
  Country('RS', 'Serbie', '381'),
  Country('SC', 'Seychelles', '248'),
  Country('SL', 'Sierra Leone', '232'),
  Country('SG', 'Singapour', '65'),
  Country('SX', 'Sint Maarten', '1721'),
  Country('SK', 'Slovaquie', '421'),
  Country('SI', 'Slovénie', '386'),
  Country('SO', 'Somalie', '252'),
  Country('SD', 'Soudan', '249'),
  Country('SS', 'Soudan du Sud', '211'),
  Country('LK', 'Sri Lanka', '94'),
  Country('SE', 'Suède', '46'),
  Country('CH', 'Suisse', '41'),
  Country('SR', 'Suriname', '597'),
  Country('SY', 'Syrie', '963'),
  Country('TJ', 'Tadjikistan', '992'),
  Country('TW', 'Taïwan', '886'),
  Country('TZ', 'Tanzanie', '255'),
  Country('TD', 'Tchad', '235'),
  Country('TH', 'Thaïlande', '66'),
  Country('TL', 'Timor oriental', '670'),
  Country('TG', 'Togo', '228'),
  Country('TK', 'Tokelau', '690'),
  Country('TO', 'Tonga', '676'),
  Country('TT', 'Trinité-et-Tobago', '1868'),
  Country('TN', 'Tunisie', '216'),
  Country('TM', 'Turkménistan', '993'),
  Country('TR', 'Turquie', '90'),
  Country('TV', 'Tuvalu', '688'),
  Country('UA', 'Ukraine', '380'),
  Country('UY', 'Uruguay', '598'),
  Country('VU', 'Vanuatu', '678'),
  Country('VA', 'Vatican', '39'),
  Country('VE', 'Venezuela', '58'),
  Country('VN', 'Viêt Nam', '84'),
  Country('WF', 'Wallis-et-Futuna', '681'),
  Country('YE', 'Yémen', '967'),
  Country('ZM', 'Zambie', '260'),
  Country('ZW', 'Zimbabwe', '263'),
];
